---
title: "Vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
---
title: "Vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### <span style="color: blue;">App Title and Authors:</span>
#### -  App Title: `DC Heat Sensitivity Mapping`

#### -  Names and course of the group members:

- Karl VonZabern - DATA 613-001
- ChihChin Yang - DATA 613-001
- SzuWei Fu - DATA 613-001
- Evan Bowman - DATA 613-001

### <span style="color: blue;">Use Case:</span>
#### - Actor Description: 

The actor for this app will most likely be someone within the DC government’s Department of Energy and Environment or Health and Human Services. The purpose of the visual representation and statistical modeling would be to assist in the formulation of policy that attempts to mitigate the occurrences of heat-related health incidences.  
 
#### - Questions of Interest: 

The use of this data frame lends itself to several questions regarding the correlates that exacerbate extreme heat and the communities most affected. Thus, our app will assist in understanding of two specific questions:

**What are environmental metrics that are correlated with Urban Heat Island Effects?**

What environmental characteristics of certain census tracts create larger heat exposure sensitivity indexes? Understanding the environmental factors would help in identifying policy approaches that would mitigate the probability of heat-induced health events. 

**What are recurring sociodemographic trends that are associated with higher heat exposure sensitivity indexes?**

Who are the communities that are at a larger risk of heat-induced health events? Identifying socio-demographic trends can assist policymakers in identifying the communities that would best benefit from policy implementation.

 
#### - Choice of approach to data: 

Our approach is to be able to map different socio-demographic metrics and environmental metrics to different Census tracts. This will allow the user to be able to visualize different metrics and how they differentiate between census tracts in DC. The modeling will also help shed insight on the magnitude of these differences. We additionally add two policy relevant data sets to map including the location and hours of cooling centers and a random sample of tree data. 

### <span style="color: blue;">Required Packages:</span>

#### Administrative Packages

shiny (Version 1.7.3): Shiny was used for base layout and skeleton code of the app as well as functions that assisted in rendering graphs, maps, models, and 
data.

thematic (Version 0.1.2.1): Thematic was used to apply a theme for the app. The theme used was thematic_shiny.

viridis (Version 0.6.2): Viridis was used to create color palettes for the graphs and maps.

#### Data Manipulation

tidyverse (Version 1.3.2): Specific tidyverse functions from packages were used to manipulate the data frame gathered from Open Data DC. Select and mutate were used heavily to obtain the correct data to work with throughout the app. 

#### Graphical Analysis

ggplot2 (Version 3.3.6): Also apart of the tidyverse, ggplot2 was used to render all graphs in the graphing tab. Functions of ggplot were utilized to successfully add logging, faceting, and smoothing options for EDA. 

#### Statistical Modeling

base (Version 4.2.1): 

#### Mapping

leaflet (Version 2.1.1): Leaflet was used to create the mapping tab of the app. A base level map was created using a shape variable for each DC census tract. More functions were used to interactively plot tract metrics, cooling center information, and tree information. 

sf (Version 1.0.8): The sf package was used in the business section to correctly manipulate the shape variable for DC census tracts into the correct format. 

### <span style="color: blue;">Data Source and Structure:</span>

#### HSEI Data

Heat Sensitivity Exposure Data was gathered from Open Data DC and contains variables related to socioeconomic, health, and environmental metrics for DC's 206 census tracts. 

#### DC Cooling Center Data

When the temperature or heat index in the District reaches 95 degrees, District Government, through the Department of Human Services (DHS) and the Homeland Security and Emergency Management Agency (HSEMA), will implement the Heat Emergency Plan and activate cooling centers for residents to seek relief. We provide locations, name of center, phone number and hours of cooling centers. 
Data comes from Open Data DC

#### DC Tree Data

DDOT's Urban Forestry Division (UFD) is the primary steward of Washington DC's ~170,000 public trees and has a mission of keeping this resource healthy, safe, & growing! Trees provide many benefits to the populations such as improving air and water quality and creates habitat for local fauna. Importantly trees are also critical for keeping the city cooler. 
Data comes from Open Data DC

## EDA Inputs, Controls, and Outputs

## Statistical Analysis Inputs, Controls, and Outputs

## References 
“Cooling Centers - District of Columbia.” Accessed December 10, 2022. https://opendata.dc.gov/datasets/cooling-centers-district-of-columbia/explore?location=38.903124,-77.008453,12.75.


“Heat Sensitivity Exposure Index.” Accessed December 10, 2022. https://opendata.dc.gov/datasets/DCGIS::heat-sensitivity-exposure-index/explore.

“Urban Forestry in DC.” Accessed December 10, 2022. https://trees.dc.gov/.
